### ISSUE TITLE
Inadvertent deletion of six website pages

### ISSUE THREAD

**Issue by martey** [PyconUK/2017.pyconuk.org#219]
#218 added a "thank you" to the site's homepage, but also removed a lot of content from the homepage. This caused a number of pages to be deleted (see ecc021e47f883ab7c23bcb457f58b194e2c7bffc) because there are now no links to some pages.

**Comment by alexwlchan** [comment]
😞 

Thanks for spotting, I’ll get this fixed. The perils of reviewing on a phone!

**Comment by alexwlchan** [comment]
@martey Thanks for letting us know – the broken content should be restored.

Please let us know if you spot anything else which is missing!

**Comment by inglesp** [comment]
Gah!  Thanks @martey for spotting and @alexwlchan for fixing.
